---
title: YARD-API Reference
output: public/doc
groups:
  - name: YARD-API
    sources:
      - README.md
  - name: Tags
    parse_titles: true
    sources: 
      - doc/tags/*.md
asset_root: doc/
assets:
  - index.html
  - index.css
  - vendor/*.js
  - vendor/*.css