---
# config/yard_api.yml
output: public/doc/api
source: doc/api
readme: doc/api/README.md
title: Rails API Project
verbose: true
debug: false
strict: false
markup:
markup_provider:
files:
  - app/controllers/**/*.rb
assets:
  images: images
  examples: examples